name: CI STG

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: [ "8.1", "8.2", "8.3" ]   # Part C: matrix

    steps:
      - name: Checkout del codi
        uses: actions/checkout@v4

      - name: Configurar PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Instal·lar dependències
        run: composer install

      - name: Executar tests
        run: ./vendor/bin/phpunit --log-junit resultats.xml   # Part D

      - name: Pujar artefacte de resultats
        if: always()                                           # Part D: sempre
        uses: actions/upload-artifact@v4
        with:
          name: resultats-XXX-php${{ matrix.php-version }}
          path: resultats.xml